"""Add category field to markets table

Revision ID: 726577ceda98
Revises: 999ba5500e63
Create Date: 2025-09-13 17:07:29.807443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726577ceda98'
down_revision = '999ba5500e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('TRADITIONAL', 'MODERN', 'GENERAL', name='marketcategory'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
