"""remove unused fields

Revision ID: 999ba5500e63
Revises: 00e17a802288
Create Date: 2025-07-26 15:21:45.690245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '999ba5500e63'
down_revision = '00e17a802288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('rating')
        batch_op.drop_column('category')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('contact_email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password')

    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('rating', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
